#!/usr/bin/env python

'''
Created by ClusterVision <infonl@clustervision.com>
This file is part of trix-status tool
https://github.com/clustervision/trix-status
trix-status is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
trix-status is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with slurm_health_checker.  If not, see <http://www.gnu.org/licenses/>.
'''

import logging
import sys
from trix_status.utils import parse_arguments

if __name__ == "__main__":
    arguments = parse_arguments()
    log = logging.getLogger('trix_status')
    log.setLevel(arguments.loglevel)

    subj = None

    if arguments.nodes:
        from trix_status import nodes as subj

    if arguments.controllers:
        from trix_status import controllers as subj

    if subj is None:
        log.error("No subject to check was specified")
        sys.exit(255)

    try:
        subj.Status(arguments).get()
    except KeyboardInterrupt:
        log.info('KeyboardInterrupt. Canceled')
