#!/usr/bin/env python

'''
Created by ClusterVision <infonl@clustervision.com>
This file is part of trix-status tool
https://github.com/clustervision/trix-status
trix-status is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
trix-status is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with slurm_health_checker.  If not, see <http://www.gnu.org/licenses/>.
'''

import logging

from trix_status import utils
from trix_status import TrixStatus

if __name__ == "__main__":
    arguments = utils.parse_arguments()
    log = logging.getLogger('trix_status')
    log.setLevel(arguments.loglevel)

    nodes = utils.get_nodes()
    TrixStatus(nodes, verbose=arguments.verbose).get()

